###
get http://localhost:3000/users


###
post http://localhost:3000/user
Content-Type: application/json

{
    "id": 3,
    "name": "KINGSMAN"
}

###

put http://localhost:3000/user
Content-Type: application/json

{
    "id":2,
    "name": "KINGSMAN"
}

###

delete http://localhost:3000/users
Content-Type: application/json

{
    "id": 2
}