###
get http://localhost:3000/user-api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hZGh1IiwiaWF0IjoxNzIwODYwNTk2LCJleHAiOjE3MjA4NjE3OTZ9.sTXqEhvavb2uOn1XuKzvkOBaHY8fkxg4jew4dycwfnA


get http://localhost:3000/user-api/users/madhu


###
post http://localhost:3000/user-api/users
Content-Type: application/json

{
    "name": "madhu babu",
    "username": "madhu",
    "password": "madhu",
    "email": "madhu@gmail.com"
}
###
post http://localhost:3000/user-api/login
Content-Type: application/json

{
    "username": "madhu",
    "password": "madhu"   
}


###

put http://localhost:3000/user-api/users/2
Content-Type: application/json

{
    "name": "KINGSMAN"
}

###

delete http://localhost:3000/user-api/users/2
