###
get http://localhost:3000/user-api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hZGh1QyIsImlhdCI6MTcyMTk3MDY3NSwiZXhwIjoxNzIyMDU3MDc1fQ.tj2AHr84pJoMnpSBg8skxrZy1y105u3R-5H1JxBvcGY
###

###
get http://localhost:3000/user-api/users/madhuC
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hZGh1QyIsImlhdCI6MTcyMTk3MDY3NSwiZXhwIjoxNzIyMDU3MDc1fQ.tj2AHr84pJoMnpSBg8skxrZy1y105u3R-5H1JxBvcGY
###

###
post http://localhost:3000/user-api/users
Content-Type: application/json

{
    "name": "madhu abcd",
    "username": "madhuC",
    "password": "madhuSC",
    "email": "madhu@gmail.com"
}
###

###
post http://localhost:3000/user-api/login
Content-Type: application/json

{
    "username": "madhuC",
    "password": "madhuSC"   
}
###

###
put http://localhost:3000/user-api/users/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hZGh1U0MiLCJpYXQiOjE3MjA4Njc0ODksImV4cCI6MTcyMDk1Mzg4OX0.6saMslggbI-TxmXaCJ5JynVDOZ-JBEuT_wjzMfgkPnI

{
    "name": "madhu",
    "username": "madhuSC",
    "password": "madhuSC",
    "email": "madhu@gmail.com"
}
###

###
delete http://localhost:3000/user-api/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hZGh1U0MiLCJpYXQiOjE3MjA4Njc0ODksImV4cCI6MTcyMDk1Mzg4OX0.6saMslggbI-TxmXaCJ5JynVDOZ-JBEuT_wjzMfgkPnI
###
